name: z Lisa Test
# just how problematic is this token??

on:
  push:

jobs:
  debug:
    runs-on: [self-hosted, npn-2CPU]
    env:
      NAME: PACKAGES_ACCESS_TOKEN
      MYSECRET: ${{ secrets.PACKAGES_ACCESS_TOKEN}}
    steps:
      - run: |
          echo "${{ env.NAME }}: ${{ env.MYSECRET }}" >> mylog.txt
        shell: bash

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: mylog.txt
          path: mylog.txt
          retention-days: 1
