#!/bin/bash

# We check this so SourceTree can handle this hook
; if [ -e ~/.bash_profile ]
; then
;     source ~/.bash_profile
; fi

# Warn if committing to master
branchName="$(git symbolic-ref --quiet --short HEAD 2> /dev/null)"
if [ "${branchName}" == "master" ] || [ "${branchName}" == "main" ]; then
  RED='\033[0;31m'
  RESET='\033[m'
  echo
  echo
  echo -e "☠️   ☠️   ${RED}WARNING:  YOU ARE COMMITTING TO MASTER !!   ☠️   ☠️"
  echo -e "☠️   ☠️   WARNING:  YOU ARE COMMITTING TO MASTER !!   ☠️   ☠️"
  echo -e "☠️   ☠️   WARNING:  YOU ARE COMMITTING TO MASTER !!   ☠️   ☠️"
  echo -e "☠️   ☠️   WARNING:  YOU ARE COMMITTING TO MASTER !!   ☠️   ☠️"
  echo -e "☠️   ☠️   WARNING:  YOU ARE COMMITTING TO MASTER !!   ☠️   ☠️"
  echo
  echo
  echo -e "Run this to undo: git reset --soft HEAD~1"
  echo -e "or this if first commit in branch/repo: git update-ref -d HEAD${RESET}"
  echo
  echo
fi

echo "Pre-commit hook ran"
exit 0
