POST https://api.github.com/repos/buildcom/the-sorting-hat/actions/workflows/release-dry-run.yml/dispatches HTTP/1.1
Accept: application/vnd.github.v3+json
content-type: application/json
Authorization: token {{$processEnv NPM_TOKEN_FERG_FULL}}

{"ref":"SODEV-34573"}

###

POST https://api.github.com/repos/buildcom/the-sorting-hat/actions/workflows/release-dev.yml/dispatches HTTP/1.1
Accept: application/vnd.github.v3+json
content-type: application/json
Authorization: token {{$processEnv NPM_TOKEN_FERG_FULL}}

{"ref":"SODEV-34573"}

###

GET https://api.github.com/repos/buildcom/react-build-store/events HTTP/1.1
Accept: application/vnd.github.v3+json
Authorization: token {{$processEnv NPM_TOKEN_FERG_FULL}}

###
GET https://api.github.com/repos/buildcom/react-build-store/events HTTP/1.1
Accept: application/vnd.github.v3+json
Authorization: token {{$processEnv NPM_TOKEN_FERG_FULL}}

###

GET https://api.github.com/repos/buildcom/react-build-store/hooks HTTP/1.1
Accept: application/vnd.github.v3+json
Authorization: token {{$processEnv NPM_TOKEN_FERG_FULL}}

###

GET https://api.github.com/apps/balrogql-bot HTTP/1.1
Accept: application/vnd.github.v3+json
Authorization: token {{$processEnv NPM_TOKEN_FERG_FULL}}

###

GET https://api.github.com/repos/buildcom/react-build-store/pulls/4685/reviews HTTP/1.1
Accept: application/vnd.github.v3+json
Authorization: token {{$processEnv NPM_TOKEN_FERG_FULL}}

###

GET https://api.github.com/repos/buildcom/react-build-store/pulls/4685/reviews/1365464982/comments HTTP/1.1
Accept: application/vnd.github.v3+json
Authorization: token {{$processEnv NPM_TOKEN_FERG_FULL}}

###

GET https://api.github.com/repos/buildcom/product-services/pulls/207 HTTP/1.1
Accept: application/vnd.github.v3+json
Authorization: token {{$processEnv NPM_TOKEN_FERG_FULL}}

###

GET https://api.github.com/repos/buildcom/product-services/pulls/207/commits HTTP/1.1
Accept: application/vnd.github.v3+json
Authorization: token {{$processEnv NPM_TOKEN_FERG_FULL}}

###

GET https://api.github.com/repos/buildcom/product-services/events HTTP/1.1
Accept: application/vnd.github.v3+json
Authorization: token {{$processEnv NPM_TOKEN_FERG_FULL}}

###

POST https://api.github.com/repos/buildcom/react-build-store/statuses/4a7999290929b19836183403db65199d2bad58f6 HTTP/1.1
Accept: Accept: application/vnd.github.v3+json
Authorization: token {{$processEnv NPM_TOKEN_FERG_FULL}}

{"state":"success"}

###

GET https://api.github.com/orgs/buildcom/settings/billing/actions HTTP/1.1
Accept: Accept: application/vnd.github.v3+json
Authorization: token {{$processEnv NPM_TOKEN_FERG_FULL}}

###

GET https://api.github.com/users/lisadean/settings/billing/actions HTTP/1.1
Accept: Accept: application/vnd.github.v3+json
Authorization: token {{$processEnv NPM_TOKEN_FERG_FULL}}

###

GET https://api.github.com/repos/buildcom/react-build-store/actions/runs/2105311595/timing HTTP/1.1
Accept: Accept: application/vnd.github.v3+json
Authorization: token {{$processEnv NPM_TOKEN_FERG_FULL}}

###

GET https://api.github.com/repos/buildcom/react-build-store/compare/e4fbea9421f1f0cfc7ef72d1cfcee54b89061457...ee58be0d5ed4b972451737e084aae64134c97cff HTTP/1.1
Accept: application/vnd.github.v3+json
content-type: application/json
Authorization: token {{$processEnv NPM_TOKEN_FERG_FULL}}

###


GET https://api.github.com/repos/lisadean/coderoaster/events HTTP/1.1
Accept: application/vnd.github.v3+json
Authorization: token {{$processEnv NPM_TOKEN_FERG_FULL}}

###

GET http://config.sys.ds.wolseley.com/react-build-store/local/ HTTP/1.1
Authorization: Basic Y29uZmlnOkNoZXZlMWxlIQ==

###
GET http://config.sys.ds.wolseley.com/react-build-store/production/ HTTP/1.1
Authorization: Basic Y29uZmlnOkNoZXZlMWxlIQ==

###

GET http://config.sys.ds.wolseley.com/build-node-store/local/ HTTP/1.1
Authorization: Basic Y29uZmlnOkNoZXZlMWxlIQ==

###

GET http://config.sys.ds.wolseley.com/store-features/production/ HTTP/1.1
Authorization: Basic Y29uZmlnOkNoZXZlMWxlIQ==

###

GET http://graphql.build.com/graphql HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtcGxveWVlSWQiOiI1MjIwIiwiY3VzdG9tZXJJZCI6MCwicHJpY2VCb29rSWQiOjF9LCJpYXQiOjE2OTIzMDQ5ODN9.AhvDeCUsFD8VdiIQrIXNBzO_K0hbSfQbSB-XIHA7nks

###

POST https://npndev.build.com/graphql HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtcGxveWVlSWQiOiI1MjIwIiwiY3VzdG9tZXJJZCI6MCwicHJpY2VCb29rSWQiOjF9LCJpYXQiOjE2OTIzMDQ5ODN9.AhvDeCUsFD8VdiIQrIXNBzO_K0hbSfQbSB-XIHA7nks
X-REQUEST-TYPE: GraphQL

query Features($featureNames: [String!]!, $path: String!) {
  features(featureNames: $featureNames, path: $path)
}

{"featureNames":["enable-vizury-opt-in-popup"],"path":"/"}

###

POST http://react-build-store-pr-50.sys.id.build.com:3001/graphql HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtcGxveWVlSWQiOiI1MjIwIiwiY3VzdG9tZXJJZCI6MCwicHJpY2VCb29rSWQiOjF9LCJpYXQiOjE2OTIzMDQ5ODN9.AhvDeCUsFD8VdiIQrIXNBzO_K0hbSfQbSB-XIHA7nks
X-REQUEST-TYPE: GraphQL

query Features($featureNames: [String!]!, $path: String!) {
  features(featureNames: $featureNames, path: $path)
}

{"featureNames":["enable-vizury-opt-in-popup"],"path":"/"}

###
POST http://react-build-store-pr-50.sys.id.build.com:3000/graphql HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtcGxveWVlSWQiOiI1MjIwIiwiY3VzdG9tZXJJZCI6MCwicHJpY2VCb29rSWQiOjF9LCJpYXQiOjE2OTIzMDQ5ODN9.AhvDeCUsFD8VdiIQrIXNBzO_K0hbSfQbSB-XIHA7nks
X-REQUEST-TYPE: GraphQL

query Features($featureNames: [String!]!, $path: String!) {
  features(featureNames: $featureNames, path: $path)
}

{"featureNames":["enable-vizury-opt-in-popup"],"path":"/"}

###

# curl -L \
#   -X POST \
#   -H "Accept: application/vnd.github+json" \
#   -H "Authorization: Bearer <YOUR-TOKEN>" \
#   -H "X-GitHub-Api-Version: 2022-11-28" \
#   https://api.github.com/repos/OWNER/REPO/check-runs \
#   -d '{"name":"mighty_readme","head_sha":"ce587453ced02b1526dfb4cb910479d431683101","status":"in_progress","external_id":"42","started_at":"2018-05-04T01:14:52Z","output":{"title":"Mighty Readme report","summary":"","text":""}}'

GET https://api.github.com/repos/buildcom/react-build-store/events HTTP/1.1
Accept: application/vnd.github.v3+json
Authorization: token {{$processEnv NPM_TOKEN_FERG_FULL}}

###

GET https://api.github.com/repos/fergdigitalcommerce/bwf-web-store/events HTTP/1.1
Accept: application/vnd.github.v3+json
Authorization: token {{$processEnv NPM_TOKEN_FERG_FULL}}

###

GET https://api.github.com/repos/fergdigitalcommerce/bwf-build-tachyons/pulls/131 HTTP/1.1
Accept: application/vnd.github.v3+json
Authorization: token {{$processEnv NPM_TOKEN_FERG_FULL}}

###
GET https://api.github.com/repos/fergdigitalcommerce/BWF-build-tachyons/events HTTP/1.1
Accept: application/vnd.github.v3+json
Authorization: token {{$processEnv NPM_TOKEN_FERG_FULL}}

###

GET https://api.github.com/orgs/fergdigitalcommerce/teams/bwf-react-developers HTTP/1.1
Accept: application/vnd.github.v3+json
Authorization: token {{$processEnv NPM_TOKEN_FERG_FULL}}
X-GitHub-Api-Version: 2022-11-28
